mysite/api/urls.py
from django.urls import path

from .views import(
    NewsUpdateAPIView,
    NewsListAPIView,
    NewsDetailAPIView,
    NewsDeleteAPIView,
    NewsCreateAPIView,
    NewsLikeAPIView,
    NewsDislikeAPIView,
   

)



urlpatterns = [
    path('',NewsListAPIView.as_view(), name='list'),
    path('new/', NewsCreateAPIView.as_view(), name='api_new'),
    path('<int:pk>/detail', NewsDetailAPIView.as_view(), name='api_detail'),
   
    path('<int:pk>/delete/', NewsDeleteAPIView.as_view(), name='api_delete'),
    path('<int:pk>/edit/',NewsUpdateAPIView.as_view(), name='api_edit'),
    path('<int:pk>/dislike',  NewsDislikeAPIView.as_view(),  name='api_dislike'),
    path('<int:pk>/like',  NewsLikeAPIView.as_view(),  name='api_like'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls')),
    path('api/',include('api.urls')),
    path('api/news/',include('commentApi.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/news/urls.py
from django.urls import path
from . import views

urlpatterns = [

  path('', views.news_list, name='news_list'),
  path('news/<int:pk>/detail/', views.news_detail, name='news_detail'),
  path('news/new/', views.news_new, name='news_new'),
  path('news/<int:pk>/delete', views.news_delete, name='news_delete'),
  path('news/<int:pk>/edit/', views.news_edit, name='news_edit'),
  path('news/<int:pk>/dislike',  views.news_dislike,  name='news_dislike'),
  path('news/<int:pk>/like',  views.news_like,  name='news_like'),
  path('category/',views.category_list, name='category_list'),
  path('category/<int:pk>/detail', views.category_detail, name='category_detail'),
  path('category/new/', views.category_new, name='category_new'),
  path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
  path('category/<int:pk>/delete', views.category_delete, name='category_delete'),
  


]

mysite/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        verbose_name_plural='Categories'
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class News(models.Model):
    class Meta:
        verbose_name_plural='News'
    author=models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    title = models.CharField(max_length=200)
    image = models.ImageField( blank=True, null=True)
    context = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
  
    text=models.TextField()
    name= models.CharField(max_length=200)
    published_date = models.DateTimeField(auto_now_add=True)
    news=models.ForeignKey(News,on_delete=models.CASCADE)


   
    def __str__(self):
        return self.name

# Create your models here.

mysite/news/forms.py
from django import forms

from .models import News,Category,Comment



class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('id',  'name',)


class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        fields = ('title', 'context',  'image',  'category',  'created_date',  'published_date',)

class CommentsForm(forms.ModelForm):
  
        
    class Meta:
        model=Comment
        fields=('text','name',)

   

mysite/news/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.utils import timezone

from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.contrib.auth.models import User

from .models import News, Category,Comment
from .forms import NewsForm, CategoryForm,CommentsForm
context = {
    'categories':Category.objects.all()
}
def news_list(request):
    news = News.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    category=Category.objects.all()
    context = {
    'categories':Category.objects.all()
    }
    context['news']=news
    return render(request, 'news/news_list.html',context)


def news_detail(request, pk):
    context = {
    'categories':Category.objects.all()
    
    }
    news = get_object_or_404(News, pk=pk)
    news.views += 1
    news.save()
    
    
    form = CommentsForm(request.POST or None )
    if form.is_valid():
        comment = form.save(commit=False)
        comment.news=news
        form.save()
            
   

    

    form = CommentsForm()
    context['form']=form
    context['news']=news
    
    
    
    return render(request, 'news/news_detail.html', context)


def news_new(request):
    context = {
    'categories':Category.objects.all()
    }
    if request.method == "POST":
        form = NewsForm(request.POST, request.FILES)
        if form.is_valid():
            news = form.save(commit=False)
            news.author = request.user
            form.save()
            return redirect('news_list')

    else:

        form = NewsForm()
        context['form']=form
    return render(request, 'news/news_edit.html', context)


def news_edit(request, pk):
    news = get_object_or_404(News, pk=pk)
    if request.method == "POST":
        form = NewsForm(request.POST,request.FILES, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.author = request.user

            form.save()
            return redirect('news_detail', pk=news.pk)

    else:

        form = NewsForm(instance=news)
    return render(request, 'news/news_edit.html', {'form': form})


def news_delete(request, pk):
    instance = News.objects.get(pk=pk)
    instance.delete()

    return redirect('news_list')


def news_dislike(request, pk):
    news = News.objects.get(pk=pk)

    news.dislike += 1

    news.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER') )


def news_like(request, pk):
    news = News.objects.get(pk=pk)

    news.like += 1

    news.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def category_list(request):
    context = {
    'categories':Category.objects.all()
    }
    category = Category.objects.order_by('name')
    context['category']= category
    return render(request, 'category/category_list.html', context)


def category_detail(request, pk):
    context = {
    'categories':Category.objects.all()
    }
    category = get_object_or_404(Category, pk=pk)
    context['category']=category
    return render(request, 'category/category_detail.html', context)


def category_new(request):
    context = {
    'categories':Category.objects.all()
    }
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid:
            form.save()

            return redirect('category_list')
    else:
        form = CategoryForm()
        context['form']=form
        return render(request, 'category/category_edit.html', context)


def category_edit(request, pk):
    
    context = {
    'categories':Category.objects.all()
    }
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()

            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
        context['form']=form
    return render(request, 'category/category_edit.html', context)


def category_delete(request, pk):
    instance = Category.objects.get(pk=pk)
    instance.delete()
    return redirect('category_list')

# Create your views here.

mysite/news/templates/category/category_detail.html
{% extends 'news/base.html' %}

{% block content %}
<!-- <a href="{% url 'category_new' %}" class="top-menu"><span class="fas fa-trash-alt"></span></a>
  <a href="{% url 'category_edit' pk=category.pk %}" class="top-menu"><span class="far fa-edit"></span></a> -->
  <h2><a href="{% url 'category_detail' pk=category.pk %}">{{category.name}} Haberleri</a></h2>
<div class="articles">
  <!-- <h1><a href="{% url 'category_list' %}">Kategoriler</a></h1> -->
  



  {% for news in category.news_set.all %}
  <div class="article">
  <h3><a href="{% url 'news_detail' pk=news.pk %}">{{news.title}}</a></h3>
  <!-- <a href="{% url 'news_edit' pk=news.pk %}"><i class="fas fa-edit"></i></a>
  <a href="{% url 'news_delete' pk=news.pk %}"><i class="fas fa-trash-alt"></i></a> -->
  <div class="news-published_date">
  <p>{{news.published_date}} tarihinde yayınlandı</p>
</div>
  
  {% if news.image %}
      <img class="card-img-top" src="{{news.image.url}}" alt="Card image cap">
     
      {% endif %}
  <p>{{ news.context|linebreaksbr|slice:":120" }}
    {% if news.context|length > 100 %}
    <a href="{% url 'news_detail' pk=news.pk %}">[...]</a>
    {% endif %}
    <p>
        <i class="fas fa-eye"></i> {{ news.views }}
     </p>
  </div>
    {% endfor %}
  
</div>
{% endblock %}

mysite/news/templates/category/category_edit.html
{% extends 'news/base.html' %}
{% load static %}
{% block content %}
    <p>Yeni Kategori</p>
    <form method="POST" enctype="category-form" >{% csrf_token %}
        {{ form.as_p }}
        {% if user.is_authenticated %}
        <button type="submit" class="save btn btn-default">Kaydet</button>
        {% endif %}
    </form>
{% endblock %}

mysite/news/templates/category/category_list.html
{% extends 'news/base.html' %}

{% block content %}
<div class="category-list_new">
<a href="{% url 'category_new' %}" class="top-menu"><i class="fas fa-plus-circle"></i>Yeni Kategori Ekle</a>
</div>  
{% for c in category %}
<div class="category-list">


<h2><a href="{% url 'category_detail' pk=c.pk %}">{{c.name}}</a>
<a href="{% url 'category_delete' pk=c.pk %}" class="top-menu"><span class="fas fa-trash"></span></a>

<a href="{% url 'category_edit' pk=c.pk %}" class="top-menu"><span class="far fa-edit"></span></a>

</h2>
</div>
{%endfor%}

{% endblock %}